export const ORDER_CREATE_INITIAL = 'ORDER_CREATE_INITIAL'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_SINGLE_INITIAL = 'ORDER_SINGLE_INITIAL'
export const ORDER_SINGLE_SUCCESS = 'ORDER_SINGLE_SUCCESS'
export const ORDER_SINGLE_FAIL = 'ORDER_SINGLE_FAIL'
export const ORDER_SINGLE_RESET = 'ORDER_SINGLE_RESET'

export const ORDER_PAY_INITIAL = 'ORDER_PAY_INITIAL'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_SINGLE_RESET'

export const ORDER_LIST_USER_INITIAL = 'ORDER_LIST_USER_INITIAL'
export const ORDER_LIST_USER_SUCCESS = 'ORDER_LIST_USER_SUCCESS'
export const ORDER_LIST_USER_FAIL = 'ORDER_LIST_USER_FAIL'
export const ORDER_LIST_USER_RESET = 'ORDER_LIST_USER_RESET'
