export const PRODUCTS_REQUEST_INITIAL = 'PRODUCTS_REQUEST_INITIAL'
export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS'
export const PRODUCTS_REQUEST_FAIL = 'PRODUCTS_REQUEST_FAIL'

export const PRODUCT_SINGLE_INITIAL = 'PRODUCT_SINGLE_INITIAL'
export const PRODUCT_SINGLE_SUCCESS = 'PRODUCT_SINGLE_SUCCESS'
export const PRODUCT_SINGLE_FAIL = 'PRODUCT_SINGLE_FAIL'
